### PR TITLE
fix!: relax pandas and pyarrow version constraints in runtime dependencies

### PR DESCRIPTION
**Pull request by danielsoeiro**
## What

Lower the runtime version constraints on `pandas` and `pyarrow` in `pyproject.toml` to minimal bounds that are known to work.

```diff
 dependencies  = [
     "polars >= 1.39.3",
-    "pandas >= 3.0.2",
-    "pyarrow >= 23.0.1"
+    "pandas >= 2.2.3",
+    "pyarrow >= 19.0.1"
 ]
```

## Why

The `pandas >= 3.0.2` and `pyarrow >= 23.0.1` constraints introduced in #90 cause a **breaking side-effect** when sparkleframe is installed as a transitive dependency inside environments that bundle older versions of these libraries.

**Concrete failure:** [flypipe](https://github.com/flypipe/flypipe) declares `sparkleframe >= 0.2`. When a Databricks job installs `flypipe==5.0.0` on **DBR 17.3** (PySpark 3.5 / pandas 2.x / older pyarrow), pip now resolves to `sparkleframe==0.7.0`, which forces `pandas >= 3.0.2` and `pyarrow >= 23.0.1`. This upgrades the runtime-bundled pandas 2.x to 3.x, and PySpark's internal `pyspark.pandas.groupby` fails at import time:

```
ImportError: cannot import name '_builtin_table' from 'pandas.core.common'
```

`pandas.core.common._builtin_table` was removed in pandas 3.0. The upgrade breaks **every** notebook task in the job (100+ tasks failed). The pyarrow pin triggers the same transitive-upgrade problem on runtimes that ship older pyarrow.

**Why the lower constraints are safe:** sparkleframe only uses basic APIs from both libraries — `pd.DataFrame` construction in `createDataFrame` and `.to_pandas()` via PyArrow in `show()`. These APIs are stable across the supported major versions, and the `pandas >= 2.2.3` / `pyarrow >= 19.0.1` combination has been validated without issues.

**After this fix:** pip can resolve to older (but still compatible) versions on runtimes like DBR 17.x, while Spark 4.x environments keep working with the newer pandas/pyarrow they ship.

> Note: `requirements-dev.txt` is intentionally not changed, so tests still run against `pandas==3.0.2` / `pyarrow==23.0.1`, preserving the CI pinning.

### CODE REVIEW

File: pyproject.toml [hunk 1]
```diff
@@ -20,7 +20,7 @@ dynamic = ["version", "description"]
 requires-python = ">=3.11"
 dependencies  = [
     "polars >= 1.39.3",
-    "pandas >= 3.0.2",
+    "pandas",
     "pyarrow >= 23.0.1"
```
Comment (oliveirafilipe) [inline pyproject.toml]:
```suggestion
    "pandas >= 2.2.3",
    "pyarrow >= 19.0.1"
```

I've tested using these two versions combined. No issues found.

Leaving them without versions is usually not ideal
For installable packages, unpinned dependencies in `[project] dependencies` mean “any version,” which:

* Makes reproducible support harder (you can’t say what you’ve actually tested).
* Lets `pip` pull very old pandas/pyarrow that might lack APIs you use.
So it’s weaker than “minimal version we know works.” A common compromise is only a lower bound (`>=`) tied to CI, not “no constraint.”

**Review by josemuller — DISMISSED** [review]

File: pyproject.toml [hunk 2]
```diff
@@ -20,8 +20,8 @@ dynamic = ["version", "description"]
 requires-python = ">=3.11"
 dependencies  = [
     "polars >= 1.39.3",
-    "pandas >= 3.0.2",
-    "pyarrow >= 23.0.1"
+    "pandas >= 2.2.3",
```
Comment (josemuller) [inline pyproject.toml:23]: why are we downgrading?

Comment (oliveirafilipe) [reply pyproject.toml:23]: We're not downgrading, we're just saying for pip that this version of sparkleframe works with any version of pandas or pyarrow above that

Comment (oliveirafilipe) [reply pyproject.toml:23]: Tests are still running against "pandas==3.0.2" and "pyarrow==23.0.1" as the `requirements-dev.txt` is not being changed

**Review by oliveirafilipe — APPROVED** [review]
